### ISSUE TITLE
Choose Isotopes to track for ROM

### ISSUE THREAD

**Issue by jbae11** [arfc/raven#3]
Ideally, all isotopes would be 'considered' for ROM generation.

However, it should be noted that that would require great computational burden.

An educated criteria should be documented on what isotopes should be tracked 

for the depletion calculation using SERPENT ROM.

The following criteria were discussed:
- [ ] Neutronics
- [ ] Decay / half life
- [ ] Radiotoxicity
- [ ] Mobility in repository (I, Cs, Tc, Sr)
- [ ] Decay Heat

**Comment by katyhuff** [comment]
closing for now. if another student wants to pick this up, reopen.
